[app]
title = MLang
package.name = mlang
package.domain = org.mlang
source.dir = .
source.include_exts = py,ml2,ml,ebnf
source.main = main.py
version = 2.2.0
requirements = python3
orientation = portrait
fullscreen = 0
# icon = assets/icon-512.png   # generated by make_icon.py from logo.png
# presplash = assets/icon-512.png
android.api = 33
android.minapi = 24
android.ndk = 25b
android.archs = arm64-v8a, armeabi-v7a
android.permissions = READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE

[buildozer]
log_level = 2
warn_on_root = 1
